### ISSUE TITLE
not support AES-128 decryption

### ISSUE THREAD

**Issue by MeMadMan** [denex/hls-downloader#1]
not support AES-128 decryption

#EXTM3U
#EXT-X-MEDIA-SEQUENCE:0
#EXT-X-ALLOW-CACHE:NO
#EXT-X-VERSION:2
#EXT-X-KEY:METHOD=AES-128,URI=

**Comment by denex** [comment]
@MeMadMan I'm sorry but Decryption doesn't supported yet. And probably will not. This project is about saving content for local playback. Mostly from Apple reference streams.
