### ISSUE TITLE
Renaming "-" in chunk to "_" cause 404 to all chunks

### ISSUE THREAD

**Issue by amotzte** [denex/hls-downloader#3]
Reproduce with 

```bash
python main.py -v  https://bitdash-a.akamaihd.net/content/sintel/hls/playlist.m3u8 ./

**Comment by denex** [comment]
Fixed

**Comment by shahinesi** [comment]
> Fixed

C:\Users\shahi\Desktop\hls-downloader-master>python main.py -v  https://cdn1live.irib.ir/live-channels/smil:nasim/playlist.m3u8?s=GNRxCLRXueTW8gbQPyzqrg&t=1577000338 ./
usage: main.py [-h] [-v] url_to_m3u8 download_dir
main.py: error: too few arguments
't' is not recognized as an internal or external command,
operable program or batch file.

**Comment by denex** [comment]
> python main.py -v https://cdn1live.irib.ir/live-channels/smil:nasim/playlist.m3u8?s=GNRxCLRXueTW8gbQPyzqrg&t=1577000338 ./

It's shell-specific issue. Shell treats symbols like `?`, '$', '=' as special.

Either escape `?` and `&` chars with `\` like this:
```sh
python main.py -v https://cdn1live.irib.ir/live-channels/smil:nasim/playlist.m3u8\?s\=GNRxCLRXueTW8gbQPyzqrg\&t\=1577000338 ./
```
Or use `'` for whole URL like this:
```sh
python main.py -v 'https://cdn1live.irib.ir/live-channels/smil:nasim/playlist.m3u8?s=GNRxCLRXueTW8gbQPyzqrg&t=1577000338' ./
```

**Comment by shahinesi** [comment]
> ```shell
> ```shell
> python main.py -v https://cdn1live.irib.ir/live-channels/smil:nasim/playlist.m3u8\?s\=GNRxCLRXueTW8gbQPyzqrg\&t\=1577000338 ./
> ```
> ```

python main.py -v https://cdn1live.irib.ir/live-channels/smil:nasim/playlist.m3u8\?s\=GNRxCLRXueTW8gbQPyzqrg\&t\=1577000338 ./
usage: main.py [-h] [-v] url_to_m3u8 download_dir
main.py: error: too few arguments
't\' is not recognized as an internal or external command,
operable program or batch file.


python main.py -v 'https://cdn1live.irib.ir/live-channels/smil:nasim/playlist.m3u8?s=GNRxCLRXueTW8gbQPyzqrg&t=1577000338' ./
usage: main.py [-h] [-v] url_to_m3u8 download_dir
main.py: error: too few arguments
't' is not recognized as an internal or external command,
operable program or batch file.
