### ISSUE TITLE
Python3 m3u8 problem

### ISSUE THREAD

**Issue by shoguevara** [denex/hls-downloader#6]
In my case I had an error loading m3u8 package, athouhg I already installed it with pip3 (for some reason is not listed in the requirements).
It can be fixed via installing a fork
`pip install --upgrade git+https://github.com/globocom/m3u8.git
`
And also, because python3 might not be the default python interpreter in the system, i prefer starting the command with python3

MacOS 10.14.6
Python 3.7.6
pip 19.3.1

**Comment by shoguevara** [comment]
Aaaand, sorry for asking, but is the script supposed to save a bunch of streaming chunks or should've it merged them in one file? I'm asking, because I only got the bunch of chunks...

**Comment by denex** [comment]
> In my case I had an error loading m3u8 package, athouhg I already installed it with pip3 (for some reason is not listed in the requirements).
> It can be fixed via installing a fork
> `pip install --upgrade git+https://github.com/globocom/m3u8.git `
> And also, because python3 might not be the default python interpreter in the system, i prefer starting the command with python3
> 
> MacOS 10.14.6
> Python 3.7.6
> pip 19.3.1

It could happened when `pip` points to another `python` binary. It's better to use following construction to be sure python use proper version of pip:
```py
python -m pip install m3u8
python -m pip list
```
or
```py
python3 -m pip install m3u8
python3 -m pip list
```

**Comment by denex** [comment]
> Aaaand, sorry for asking, but is the script supposed to save a bunch of streaming chunks or should've it merged them in one file? I'm asking, because I only got the bunch of chunks...

This script does not combine chunks. But you can do it after all content downloaded with `ffmpeg` like described here [https://superuser.com/a/693009](https://superuser.com/a/693009)
