### ISSUE TITLE
TypeError: slugify() got an unexpected keyword argument 'lowercase'

### ISSUE THREAD

**Issue by tablecell** [denex/hls-downloader#8]
File " hls-downloader\downloader.py", line 30, in filter_filename_part
    result = slugify.slugify(string, lowercase=False, regex_pattern=allowed_pattern)
TypeError: slugify() got an unexpected keyword argument 'lowercase'

testslug.py
```
import slugify
import re


def test(string,allowed_pattern=re.compile(r'[^-.@!\w]+', re.IGNORECASE)):
      
        result = slugify.slugify(string, lowercase=False, regex_pattern=allowed_pattern)
        return result
        
        
string="some"


test(string)          
```
Traceback (most recent call last):
  File "testslug.py", line 14, in <module>
    test(string)
  File "testslug.py", line 7, in test
    result = slugify.slugify(string, lowercase=False, regex_pattern=allowed_pattern)
TypeError: slugify() got an unexpected keyword argument 'lowercase'

**Comment by denex** [comment]
@tablecell could you please specify which version of `slugify` you are using?
I've checked versions 2.x, 3.x and 4.x. And all have `lowercase` parameter.
See [Slugify source code](https://github.com/un33k/python-slugify/blob/d1599a799d551d6bf57b1a727af10c125fc6a257/slugify/slugify.py#L78)

**Comment by suntengfeisun** [comment]
Hi, I have the same question a hours ago.
I think u install specify use "pip install specify" ,but it's wrong.
u should use "pip install python-slugify".
enjoy it.

**Comment by denex** [comment]
Could you please call `pip list` command? To see which version of `python-slugify` you have.

**Comment by tablecell** [comment]
> 
> 
> Could you please call `pip list` command? To see which version of `python-slugify` you have.
```
python -m pip install -r requirements    
```
  solved the  problem

**Comment by wpyoga** [comment]
I ran into this same issue today. The mistake was running `pip install slugify` instead of `pip install python-slugify`.
